# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 10, 9, 18, 22, 11, 773166)),
        ),
    ]
