# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 22:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('date_added', models.DateField(default=datetime.datetime(2017, 10, 11, 22, 2, 20, 973802))),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('Category', models.CharField(max_length=128)),
                ('is_favorite', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('date_added', models.DateField(default=datetime.datetime(2017, 10, 11, 22, 2, 20, 973362))),
            ],
        ),
    ]
