# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 10, 11, 22, 5, 31, 281604)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 10, 11, 22, 5, 31, 281159)),
        ),
    ]
